### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by Naereen** [o0morgan0o/CisterianNumbers#1]
Hello,
Could you [choose a license](https://choosealicense.com/) and specify if this project is open-source or not?
Unless specified explicitly, a project stays closed-source, even if the files are on GitHub, see [this explanation](https://choosealicense.com/no-permission/).
Thanks in advance!
Regards, -- @Naereen

**Comment by o0morgan0o** [comment]
Hello, because the project is based on p5js and p5.js-svg, all under GNU Lesser General Public License v2.1, this falls into the same conditions. Added in the project. Thanks.

**Comment by Naereen** [comment]
Hi @o0morgan0o,
Thanks for your (quick!) reply!
You're welcome.
A lot of people forget, I try to open tiny issues like this whenever I can!
