### ISSUE TITLE
Would it be hard to provide a *font* that allows to display these symbols inline some text?

### ISSUE THREAD

**Issue by Naereen** [o0morgan0o/CisterianNumbers#3]
I would be curious to know if it would be hard to provide a *font* that allows to display these Cisterian Numbers symbols inline some text?

Based on the SVG that your app can generate, I guess it shouldn't be too hard to bundle it in a font, similar to what Font-Awesome does for instance.

I don't know how it could be used at the end in a webpage, but having something like
```html
This number 1234 is written <span class="cisterian">1234</span>
```
which could display the *content* of the `<span>...</span>` using the font, or your Javascript program, that would be awesome.

Let me know what you think!

**Comment by o0morgan0o** [comment]
I really don't know how to do this in an efficient and compact way,  i think your approach similar to Font-Awesome is very interesting.

**Comment by Naereen** [comment]
Creating a font based on  SVG symbols for each glyph is apparently not so hard, see <http://tex.stackexchange.com/questions/22487/ddg#22493> for instance

I think the hardest part would be to have ligatures to allow numbers with more than one digit, e.g., 1234, to be represented by a single glyph and not four glyphs. I don't know how to tackle that...

Even for basic ligatures like fi or ff, I tried and failed in 2018 on a completely different project (see https://github.com/Naereen/fontify/issues/3). I just know it's not easy...

**Comment by Naereen** [comment]
I honestly won't have time to try this.

https://www.youtube.com/watch?v=ZGpM7rXCHGI can give ideas.

**Comment by o0morgan0o** [comment]
I think the pull request #5 provides some ideas about this.
